name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request: ~

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: Debug

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: kostareg
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Configure CMake
        run: |
          nix develop --command cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: nix develop --command cmake --build build --config ${{ matrix.build_type }}

      - name: Run Benchmarks
        run: nix develop --command ./build/benchmarks/benchmarks --benchmark_out=benchmark_results.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Google Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '110%'
          comment-on-alert: true
          fail-on-alert: true
