name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request: ~

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: kostareg
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Configure CMake with Coverage
        run: |
          nix develop --command cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_C_FLAGS="--coverage"

      - name: Build
        run: nix develop --command cmake --build build

      - name: Run Tests
        run: nix develop --command ctest --test-dir build

      - name: Generate Coverage Report
        run: |
          nix develop --command gcovr --gcov-executable="llvm-cov gcov" --gcov-ignore-errors=no_working_dir_found --exclude '.*_deps/googletest-src/.*' --object-directory build --root . --html --html-details -o coverage.html
          nix develop --command gcovr --gcov-executable="llvm-cov gcov" --gcov-ignore-errors=no_working_dir_found --exclude '.*_deps/googletest-src/.*' --object-directory build --root . --xml -o coverage.xml

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.html
            coverage.xml
